[tool.poetry]
name = "quran-server"
version = "0.1.0"
description = "Server API used for Bless app"
authors = ["Iqbal Syifa Mahmuda <bal.mahmuda@gmail.com>"]
license = "GPL-3.0-only"
readme = "README.md"
packages = [{include = "quran_server"}]

[tool.poetry.dependencies]
python = "^3.10"
Django = "^4.1.5"
djangorestframework = "^3.14.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
