# Generated by Django 4.1.5 on 2023-01-08 10:17
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Quran",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("surat", models.IntegerField()),
                ("ayat", models.IntegerField()),
                ("text", models.TextField()),
            ],
            options={
                "verbose_name_plural": "Qur'an",
                "ordering": ["surat", "ayat"],
            },
        ),
        migrations.CreateModel(
            name="TranslationVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Translation Versions",
                "ordering": ["version"],
            },
        ),
        migrations.CreateModel(
            name="Translation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.TextField()),
                (
                    "quran",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dquran.quran"
                    ),
                ),
                (
                    "translation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dquran.translationversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Translations",
                "ordering": ["quran", "translation_version"],
            },
        ),
    ]
