# Generated by Django 4.1.5 on 2023-02-23 10:26
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0003_alter_quran_surat"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbstractAyatship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Ayat",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AyatTranslation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("translation", models.TextField()),
                (
                    "ayat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dquran.ayat"
                    ),
                ),
                (
                    "translation_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dquran.translationversion",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Translations",
                "ordering": ["ayat", "translation_version"],
            },
        ),
        migrations.CreateModel(
            name="Surat",
            fields=[
                (
                    "number",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=1000)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="translation",
            name="quran",
        ),
        migrations.RemoveField(
            model_name="translation",
            name="translation_version",
        ),
        migrations.CreateModel(
            name="Ayatship",
            fields=[
                (
                    "abstractayatship_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="dquran.abstractayatship",
                    ),
                ),
            ],
            bases=("dquran.abstractayatship",),
        ),
        migrations.DeleteModel(
            name="Quran",
        ),
        migrations.DeleteModel(
            name="Translation",
        ),
        migrations.AddField(
            model_name="abstractayatship",
            name="ayat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dquran.ayat"
            ),
        ),
        migrations.AddField(
            model_name="abstractayatship",
            name="surat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="dquran.surat"
            ),
        ),
        migrations.AddField(
            model_name="surat",
            name="ayats",
            field=models.ManyToManyField(through="dquran.Ayatship", to="dquran.ayat"),
        ),
    ]
