# Generated by Django 4.1.5 on 2023-02-23 11:54
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0004_abstractayatship_ayat_ayattranslation_surat_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AyatTranslation",
        ),
        migrations.DeleteModel(
            name="TranslationVersion",
        ),
    ]
