# Generated by Django 4.1.5 on 2023-02-24 04:28
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0006_remove_surat_ayats_delete_ayatship"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AbstractAyatship",
        ),
    ]
