# Generated by Django 4.1.5 on 2023-02-24 04:34
import uuid

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0007_delete_abstractayatship"),
    ]

    operations = [
        migrations.CreateModel(
            name="Ayatship",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.PositiveIntegerField()),
                (
                    "ayat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dquran.ayat"
                    ),
                ),
                (
                    "surat",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="dquran.surat"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="surat",
            name="ayats",
            field=models.ManyToManyField(through="dquran.Ayatship", to="dquran.ayat"),
        ),
    ]
