# Generated by Django 4.1.5 on 2023-02-24 08:04
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0008_ayatship_surat_ayats"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ayatship",
            options={"ordering": ("surat", "number")},
        ),
        migrations.AlterModelOptions(
            name="surat",
            options={"ordering": ("number",)},
        ),
    ]
