# Generated by Django 4.1.5 on 2023-02-26 04:00
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0010_surat_opened_with_basmallah"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ayatship",
            unique_together={("surat", "number")},
        ),
    ]
