# Generated by Django 4.1.5 on 2023-02-28 04:38
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("dquran", "0011_alter_ayatship_unique_together"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="surat",
            name="opened_with_basmallah",
        ),
    ]
